sphinx-contrib/sphinxcontrib-towncrier

- .gitignore
- pyproject.toml
- setup.cfg
It's what I have for now.
I haven't specify any info about python versions and Operating System. Also I put into `pyproject.toml` only essential configs. I'm sure I should add more configs, please let me know which one.
And actually I wasn't able to run `python -c 'from sphinxcontrib.towncrier import TowncrierDraftEntriesDirective, setup'` even though all installation/test steps from #4 passed without issues and nothing explodes.
Running `pip freeze` shows `sphinxcontrib-towncrier` as installed but I receive `ModuleNotFoundError: No module named 'sphinxcontrib'` error.  I'm not sure what's wrong.
> Add configs for packaging

- setup.cfg
Links were replaced to new ones while dist name already was `sphinxcontrib-towncrier` in `setup.cfg` so it's left unchanged.
Close #11
> Replace old repo links with new ones

- src/sphinxcontrib/towncrier/__init__.py
This change addresses #1 only partially and as such it needs a
follow-up.
The solution is suboptimal because it forces Sphinx to rebuild
documents regardless of whether the news fragments have changed in any
way.
OTOH, using `BuildEnvironment.note_dependency()` would be rather
useless in `TowncrierDraftEntriesDirective.run()` since it'd only make
it depend on the existing fragment changes (that almost never happens)
and would ignore any new fragments appearing on disk (because the only
dependencies declared would be the ones that existed at the time of
the first directive run).
The next step would be implementing tracking of the fragments outside
of the directive using 'env-get-outdated' combined with tracking of
the documents that use the directive via `BuildEnvironment` custom
attribute …
> 📝 Rebuild any documents using the directive

- tox.ini
Now it's possible to produce dist under `dist/` folder with `tox -e build-dist`.
Local smoke tests works fine.
Close #19
> Add a tox config with `build-dists` env

- tox.ini
This will fix [failed](https://github.com/slsh1o/towncrier/runs/990026822?check_suite_focus=true#step:11:18) actions in `toxenvs:build-dists` .
> Fix build-dists command flow to ignore `No such file or directory` error

- .github/workflows/tox-linters.yaml
Everything should be fine but I am not sure about a `-e lint` flag in commands that run tox because in the `matrix` I've set `TOXENV: lint`, need some clarification here.
Also, I added python versions from 3.6 to 3.9 to the `matrix`, if we need only 3.8 I will delete others.
Close #22
> Add GitHub Actions workflows for `toxenv:lint`

- .pylintrc
This change:
* makes pylint use parallelism for faster execution
* adjusts the good var names list
* enables name hints
* allows taking import fallbacks into account
* helps maintain the usage of pytest while avoiding stdlib unittest
> Improve pylint config with project-specific settings

- .flake8
- mypy.ini
- src/sphinxcontrib/towncrier/__init__.py
Closes #1 
This is very very early stage code.
I'm kinda assured that we'll need to deal with absolute vs relative path.
The current state of the repo doesn't easily allow to test, even manually, that something works. So this is the first step exploring this issue, but It's absolutely not ready for merging. Ooooor you can merge and fix later, anyway, the lib is not usable as-is, so it's not very different from being broken :D
Good luck for setting up all the boilerplate !
> 🐛 Implement rebuilding documents with the directive on fragments changes granularly

- .github/workflows/tox-tests.yaml
Because of near-future [changes](https://github.blog/changelog/2020-10-29-github-actions-ubuntu-latest-workflows-will-use-ubuntu-20-04/) to the `ubuntu-latest` version on GHA. The current `ubuntu-latest` version was changed explicitly to `18-04`.
> Change ubuntu-latest to 18.04 in GHA

- .github/workflows/tox-linters.yaml
Switch missed `env.PY_SHA256` to the hash calculated by another step.
> Fix pre-commit py_hash_key in GHA

- .github/workflows/tox-tests.yaml
This change drops "tag push" runs and direct pushes by dependabot.
> Reduce the number of duplicate GHA workflows

- .github/workflows/tox-tests.yaml
This change essentially corrects a typo in the conditional that was meant to filter
out branch creation workflows but keep the tag creations running.
> 🐛 Fix getting ref_type from github.event @ GHA

- src/sphinxcontrib/towncrier/__init__.py
Version 21.9.0rc1 of towncrier introduced ``--version`` for the tool,
which means that, if you want to pass ``--version`` when building the
changelog, you **must** pass the ``build`` command and not rely on the
default command being ``build``.
> Support towncrier >= 21.9.0rc1

- .github/workflows/tox-tests.yaml
- src/sphinxcontrib/towncrier/_towncrier.py
This patch implements compatibility with the newly released `towncrier >= 22.8.0rc1`. Since the extension relies on the Towncrier's private API, this sort of thing is bound to happen time to time. It is solved by using a fallback import logic.
This change also adds the said Towncrier version to the CI matrix.
Fixes #60.
> Adjust the config loader import to support `towncrier >= 22.8.0rc1`

- src/sphinxcontrib/towncrier/__init__.py
- src/sphinxcontrib/towncrier/_data_transformers.py
- tests/_data_transformers_test.py
- tests/units_test.py
I was running into some issues with a random `\` being added at the beginning of my draft changelog. I am not using the default RST parser, instead I am making use of a Markdown one, which made the character visible instead of rendering as an empty character.
Hopefully adding it only when needed is a valid solution to this issue! Let me know if there is anything I am missing from the PR.
Would also like to kindly ask for a release when this PR is merged, as the project seems stable enough and doesnt receive any consistent releases :)
> Escape RST substitution only when needed

- src/sphinxcontrib/towncrier/_towncrier.py
- src/sphinxcontrib/towncrier/ext.py
Fixes breaks because of https://github.com/twisted/towncrier/pull/429
> Transform dataclass to dict for towncrier>=22.12.0

- src/sphinxcontrib/towncrier/_fragment_discovery.py
- src/sphinxcontrib/towncrier/ext.py
- tests/_fragment_discovery_test.py
- tests/units_test.py
Fixes #81 
- Extract helper function for finding the config file.
- Refactor _find_config_file for simplicity.
- Refactor to generalize the search across a list of two candidates.
- Re-order search path for config files to match towncrier.
> Prefer `towncrier.toml` over `pyproject.toml` if present

- pyproject.toml
pyproject.toml:
Update setuptools-scm to >= 7.1.0 to drop the requirement for setuptools-scm-git-archive (since the functionality is included since 7.0.0).
Update requirement for setuptools accordingly.
> Update build-system dependencies

- src/sphinxcontrib/towncrier/_fragment_discovery.py
@webknjaz  this is a first pass at solving this problem, feel free to suggest alternative approaches to tackling the issue. Ultimately it is very simple to solve for only new Towncrier, but maintaining backwards compatibility is more difficult. In the end I opted to basically have side by side implementations of the key `lookup_towncrier_fragments()` function. This means that there is a little bit more duplicated code between the two versions than there needs to be, but it also means that when/if support for pre 24.7 Towncrier is dropped it will be easy to just delete the older function. I can change this if you prefer a single function.
I also renamed `get_towncrier_config()` to `get_towncrier_config_as_dict()` to make way for a new version of `get_towncrier_config()` returning the new …
> Make the project compatible with Towncrier >= 24.7

- .github/stdlib-workflows/reusable-tox/actions/post-src-checkout/action.yml
- .github/workflows/reusable-tox.yml
This patch introduces a concept of hooks to reusable workflows, starting with post-src-checkout.
> 🧪💅 Move caching pre-commit venvs to a hook
